### ISSUE TITLE
Top scale doesn't line up with drops and not all drops initially displayed

### ISSUE THREAD

**Issue by rteristi** [marmelab/EventDrops#89] opened 2016-08-02 13:05 UTC
The dots do not appear to line up with the labels on the top scale, either before or after zooming.

Also, when the chart is first displayed, not all of the drops are shown. If I drag the chart right or left, or scroll out, I can see the other drops. Should I see all drops when the chart is initially displayed?

JSFiddle using eventDrops master: https://jsfiddle.net/rteristi/ewvc8ttf/

Expected behavior (eventDrops 1.2): https://jsfiddle.net/rteristi/mczhgskL/

Screenshot of problem:
![image](https://cloud.githubusercontent.com/assets/3999792/17329065/e0c0beda-588e-11e6-973d-1fed83bbd41f.png)

The behavior is consistent in Chrome and Firefox.

**Comment by MariasStory** [comment] 2016-08-02 19:31
Similar comment there: #85

**Comment by jasonnormandin** [comment] 2016-09-13 20:25
I am also seeing this problem.

![mozilla_firefox](https://cloud.githubusercontent.com/assets/16721715/18490130/ac2d947a-79ce-11e6-9cc6-265fd8b74f9a.jpg)

**Comment by jpetitcolas** [comment] 2018-01-30 17:36
We released a new `1.0.0` version (see [our blog post](https://marmelab.com/blog/2018/01/26/event-drops-1.0-is-out.html) to see what changed). My comment relies on this new version.

> Also, when the chart is first displayed, not all of the drops are shown.

This is the expected behavior. By default, we display drops only between today and one year ago. If you want to change this behavior, you can use `range.start` and `range.end` configuration parameters. See [configuration reference](https://github.com/marmelab/EventDrops/blob/master/docs/configuration.md) for more details.

> The dots do not appear to line up with the labels on the top scale, either before or after zooming.

I can't reproduce. Can you give us a snippet to reproduce the issue? Is it still happening with the latest version?

**Comment by jpetitcolas** [comment] 2018-02-14 16:53
Looks like the bug you show me @Kmaschta, doesn't it?

**Comment by jpetitcolas** [comment] 2018-03-20 20:24
Closing as no feedback. Feel free to re-open it if you still encounter the issue.

**Closed by jpetitcolas** 2018-03-20 20:24 UTC
Labels: bug
