### ISSUE TITLE
Individual drop color is calculated wrong when adding/removing drops from viewport

### ISSUE THREAD

**Issue by lajtmaN** [marmelab/EventDrops#239] opened 2018-05-02 11:03 UTC
I use inidividually colored drops, which is colored based on some data related to each drop.
When panning or zooming the timelines and new drops appear, the color changes on all drops on that line, instead of only the new drop.

Please see this example: https://a.uguu.se/UP4TCkFVGhWg_2018-05-02_13-02-12.mp4
It is expected that the red drop remains red and not change to green.

* EventDrops version: 1.2.0

**Comment by martyquinn** [comment] 2018-05-22 19:19
I just opened what appears to be a duplicate of this issue and I see no one has responded in 20 days. This is not a good sign. I'll make a note in my new issue pointing to this one.

**Comment by jpetitcolas** [comment] 2018-05-23 07:12
@martyquinn: don't worry, this project is not dead, even if no activity in last weeks. We are working on this project on our spare time, and hence, we don't guarantee any resolution time. But we'll take a look on it.

**Comment by sealightPT** [comment] 2018-06-29 15:48
A similar problem occurs with radius. If we have a radius function which depends of the data point when panning or zooming the timelines and new drops appear, the radius changes on all drops on that line, instead of only the new drop. 
When zoomed out the point radius isn't honored. We can have a huge circle almost hidden that only becomes visible when zooming in.

**Closed** 2019-01-05 11:20 UTC
Labels: bug
