### ISSUE TITLE
Custom data per event

### ISSUE THREAD

**Issue by rusu-robert** [marmelab/EventDrops#26] opened 2015-05-24 10:52 UTC
Hello, 
this is a very nice tool and I think  adding new features would make it even more awesome! 

One of the features which might be implemented is offering custom data for each event, thus one can use different colors for the event drops considering some specific business logic. Also one could show different information regarding the event over which a user hovers. Someone built something similar to this (check http://hoonzis.blogspot.com/2014/11/events-visualization-with-evendrops-and.html) however latest version does not seem to work properly.

Best regards,
Robert

**Comment by fzaninotto** [comment] 2015-05-26 14:11
Thanks for your feedback!

Your request is a duplicate of #20.

**Closed by fzaninotto** 2015-05-26 14:11 UTC
