### ISSUE TITLE
Circles not metaballing?

### ISSUE THREAD

**Issue by infinity77** [marmelab/EventDrops#105] opened 2016-09-30 11:15 UTC
First of all, thank you for developing such a nice library.

I have an issue in which the metaballs seems not to be doing what they should (or at least the way I understood them...). I have daily data, and for some hours of the day I have more than 70 events per hour (!). However, when I initialize the chart like this:

``` js
const chart = d3.chart.eventDrops()
    .start(new Date(new Date(2016, 1, 9, 23, 59))) // day before
    .end(new Date(2016, 1, 11, 20, 0))  // day after with some margin...
    .date(function(d) {;
        return parseDate(d.date);
    })`
```

I can see that all the dots have the same size (i.e., there is no "merging" of very close dots to make bigger metaballs), although they're only separated by mere minutes (over the span of 2 days in the axes start and end dates). 

Working JSFiddle here: [https://jsfiddle.net/Infinity77/0x3L6gj9/3/](https://jsfiddle.net/Infinity77/0x3L6gj9/3/)

If this is not how the library is supposed to work, could you tell me how to modify it to make the metaballs appear for those high frequency hourly events?

I attach a plot of the frequency of the data, just in case...

Thank you in advance for your help.

![image](https://cloud.githubusercontent.com/assets/8988321/18990075/ef05c058-870f-11e6-845f-d0716454ae21.png)

**Comment by jpheintz** [comment] 2017-01-12 15:44
I experiencing the same problem with events not merging into the large graphic.

**Comment by jpetitcolas** [comment] 2018-03-22 16:53
It seems the issue is fixed in the last version (see [JSFiddle](https://jsfiddle.net/LudaL34o/3/)). Closing the issue, as we don't support previous one. Check the [migration guide](https://github.com/marmelab/EventDrops/blob/master/MIGRATION-1.0.md) for further information. :)

**Closed by jpetitcolas** 2018-03-22 16:53 UTC
Labels: help wanted
