### ISSUE TITLE
EventDrops Scroll on drop container issue

### ISSUE THREAD

**Issue by Rekhajikki** [marmelab/EventDrops#85] opened 2016-07-08 12:43 UTC
On the scroll of drops-container the drop-line overwhelm the labels.kindly find the below snapshot attached .Kindly help me out to fix the issue.

Thanks,
Rekha Jikki
![captureeventdrops](https://cloud.githubusercontent.com/assets/19817281/16687659/9e124334-4537-11e6-891a-47f3ca4416c6.PNG)

**Comment by jpetitcolas** [comment] 2016-07-11 15:14
I can't reproduce the issue on the [demo](www.marmelab.com/EventDrops).

Which browser and version are you using? Can you provide us your code?

**Comment by MariasStory** [comment] 2016-07-19 08:41
I don't see exactly this issue. In my case the time scale changes with zoom.
This is what I get for recent events:
![image](https://cloud.githubusercontent.com/assets/6576335/16943632/f49af1d4-4d9c-11e6-8f89-532bbc8214c5.png)

BZW: I am using the GitHub version.

**Comment by MariasStory** [comment] 2016-07-31 08:49
The demo you refereed to does not work.

**Comment by Rekhajikki** [comment] 2016-09-22 12:05
Hi ,

I'm using the event drops plugin in ember app.Seems like the filter and clipPath will not work as expected in svg in ember app.Kindly help me out to fix the issue.
I tried to fix following the below link
 http://stackoverflow.com/questions/26135065/broken-svg-filter-id-link-when-using-history-api-with-ember-cli/31303293#31303293 

but it did not work out for me.

Thanks,
Rekha Jikki

**Comment by jpetitcolas** [comment] 2017-03-28 07:00
@Rekhajikki: can you open a separate issue? It doesn't seem related to the one starting this discussion, does it? :)

**Comment by jpetitcolas** [comment] 2017-08-28 16:26
@MariasStory: fixed demo link is: https://marmelab.com/EventDrops/

Closing the issue as I can't reproduce it. Feel free to re-open it if it is still the case. :)

**Closed by jpetitcolas** 2017-08-28 16:26 UTC
Labels: bug
